name: Actualizar Noticias

on:
  schedule:
    # 13:00 UTC = 08:00 hora de Perú
    - cron: "0 13 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  actualizar-noticias:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4 feedparser

      - name: Actualizar noticias
        run: python actualizar_noticias.py

      - name: Guardar cambios
        run: |

          git config user.name "github-actions[bot]"

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add noticias.json

          git diff --cached --quiet || git commit -m "Actualizar noticias"

          git push
